language: php
php:
 - 5.3

env:
  matrix:
   #- DB=MYSQL CORE_RELEASE=3.0
   - DB=MYSQL CORE_RELEASE=3.1
   #- DB=MYSQL CORE_RELEASE=master
   - DB=PGSQL CORE_RELEASE=3.1
   - DB=SQLITE CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.1
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.1
      #env: DB=MYSQL CORE_RELEASE=master

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
- vendor/bin/phpunit dynamic-core/tests/
notifications:
  slack:
    secure: pUlNZmgSU8ZCwfvL0KCCKglZKTvI8oJIAK1bkTENtWRPU6a1so2XDWzsxIoZC9VcvbycOogk7bbYTSyFWZVyhv777CIp4voxlH+DQ9U2LCbibAbXXOWc9cEEo8o2t2KerI8zA1P+kdXDXNjTNyGNXVLickIDFWHqe7570kBt4uQ=