mappings:
  TagAdmin: Dynamic\Core\Admin\TagAdmin
  SpiffAdmin: Dynamic\Core\Admin\SpiffAdmin
  FooterLinksLegacy: Dynamic\Core\ORM\FooterLinksLegacy
  SpiffManager: Dynamic\Core\ORM\SpiffManager
  VirtualPageExtension: Dynamic\Core\ORM\VirtualPageExtension
  YoutubeField: Dynamic\Core\Form\YoutubeField
  HolderItem: Dynamic\Core\Page\HolderItem
  HolderItem_Controller: Dynamic\Core\Page\HolderItemController
  HolderPage: Dynamic\Core\Page\HolderPage
  HolderPage_Controller: Dynamic\Core\Page\HolderPageController
  DetailPage: Dynamic\Core\Page\DetailPage
  DetailPage_Controller: Dynamic\Core\Page\DetailPageController
  SectionPage: Dynamic\Core\Page\SectionPage
  SectionPage_Controller: Dynamic\Core\Page\SectionPageController
  CollectionPage: Dynamic\Core\Page\CollectionPage
  CollectionPage_Controller: Dynamic\Core\Page\CollectionPageController
  LinkObject: Dynamic\Core\Model\LinkObject
  Tag: Dynamic\Core\Model\Tag
  Spiff: Dynamic\Core\Model\Spiff
  TextPage: Dynamic\Core\Page\TextPage
  TextPage_Controller: Dynamic\Core\Page\TextPageController
  DynamicHomePage: Dynamic\Core\Page\DynamicHomePage
  DynamicHomePage_Controller: Dynamic\Core\Page\DynamicHomePageController
  FormPage: Dynamic\Core\Page\FormPage
  FormPage_Controller: Dynamic\Core\Page\FormPageController
  NewsHolder: Dynamic\Core\Page\NewsHolder
  NewsHolder_Controller: Dynamic\Core\Page\NewsHolderController
  LandingPage: Dynamic\Core\Page\LandingPage
  LandingPage_Controller: Dynamic\Core\Page\LandingPageController
  NewsArticle: Dynamic\Core\Page\NewsArticle
  NewsArticle_Controller: Dynamic\Core\Page\NewsArticleController
  BasicPage: Dynamic\Core\Page\BasicPage
  BasicPage_Controller: Dynamic\Core\Page\BasicPageController
  ContactPage: Dynamic\Core\Page\ContactPage
  ContactPage_Controller: Dynamic\Core\Page\ContactPageController
  SiteMap: Dynamic\Core\Page\SiteMap
  SiteMap_Controller: Dynamic\Core\Page\SiteMapController
  NewsGroupPage: Dynamic\Core\Page\NewsGroupPage
  NewsGroupPage_Controller: Dynamic\Core\Page\NewsGroupPageController
  SearchPage: Dynamic\Core\Page\SearchPage
  SearchPage_Controller: Dynamic\Core\Page\SearchPageController
  UnusedPageTypesReport: Dynamic\Core\Report\UnusedPageTypesReport
  SpiffLinkableUpdateTask: Dynamic\Core\Task\SpiffLinkableUpdateTask
  CompanyConfigTask: Dynamic\Core\Task\CompanyConfigTask
  PreviewExtensionMigrationTask: Dynamic\Core\Task\PreviewExtensionMigrationTask
  DynamicHomePageTest: Dynamic\Core\Test\DynamicHomePageTest
  ContactPageTest: Dynamic\Core\Test\ContactPageTest
  FormPageTest: Dynamic\Core\Test\FormPageTest
  YoutubeFieldTest: Dynamic\Core\Test\YoutubeFieldTest
  YoutubeFieldTest_Validator: Dynamic\Core\Test\YoutubeFieldTest_Validator
  YoutubeFieldTest_Controller: Dynamic\Core\Test\YoutubeFieldTestController
  NewsArticleTest: Dynamic\Core\Test\NewsArticleTest
  LandingPageTest: Dynamic\Core\Test\LandingPageTest
  DetailPageTest: Dynamic\Core\Test\DetailPageTest
  DC_Test: Dynamic\Core\Test\DC_Test
  BasicPageTest: Dynamic\Core\Test\BasicPageTest
