mappings:
  TagAdmin: Dynamic\Core\Admin\TagAdmin
  SpiffAdmin: Dynamic\Core\Admin\SpiffAdmin
  FooterLinksLegacy: Dynamic\Core\ORM\FooterLinksLegacy
  SpiffManager: Dynamic\Core\ORM\SpiffManager
  VirtualPageExtension: Dynamic\Core\ORM\VirtualPageExtension
  YoutubeField: Dynamic\Core\Form\YoutubeField
  HolderItem: Dynamic\Core\Model\HolderItem
  HolderItem_Controller: Dynamic\Core\Model\HolderItem_Controller
  HolderPage: Dynamic\Core\Model\HolderPage
  HolderPage_Controller: Dynamic\Core\Model\HolderPage_Controller
  DetailPage: Dynamic\Core\Model\DetailPage
  DetailPage_Controller: Dynamic\Core\Model\DetailPage_Controller
  SectionPage: Dynamic\Core\Model\SectionPage
  SectionPage_Controller: Dynamic\Core\Model\SectionPage_Controller
  CollectionPage: Dynamic\Core\Model\CollectionPage
  CollectionPage_Controller: Dynamic\Core\Model\CollectionPage_Controller
  LinkObject: Dynamic\Core\Object\LinkObject
  Tag: Dynamic\Core\Object\Tag
  Spiff: Dynamic\Core\Object\Spiff
  TextPage: Dynamic\Core\Page\TextPage
  TextPage_Controller: Dynamic\Core\Page\TextPage_Controller
  DynamicHomePage: Dynamic\Core\Page\DynamicHomePage
  DynamicHomePage_Controller: Dynamic\Core\Page\DynamicHomePage_Controller
  FormPage: Dynamic\Core\Page\FormPage
  FormPage_Controller: Dynamic\Core\Page\FormPage_Controller
  NewsHolder: Dynamic\Core\Page\NewsHolder
  NewsHolder_Controller: Dynamic\Core\Page\NewsHolder_Controller
  LandingPage: Dynamic\Core\Page\LandingPage
  LandingPage_Controller: Dynamic\Core\Page\LandingPage_Controller
  NewsArticle: Dynamic\Core\Page\NewsArticle
  NewsArticle_Controller: Dynamic\Core\Page\NewsArticle_Controller
  BasicPage: Dynamic\Core\Page\BasicPage
  BasicPage_Controller: Dynamic\Core\Page\BasicPage_Controller
  ContactPage: Dynamic\Core\Page\ContactPage
  ContactPage_Controller: Dynamic\Core\Page\ContactPage_Controller
  SiteMap: Dynamic\Core\Page\SiteMap
  SiteMap_Controller: Dynamic\Core\Page\SiteMap_Controller
  NewsGroupPage: Dynamic\Core\Page\NewsGroupPage
  NewsGroupPage_Controller: Dynamic\Core\Page\NewsGroupPage_Controller
  SearchPage: Dynamic\Core\Page\SearchPage
  SearchPage_Controller: Dynamic\Core\Page\SearchPage_Controller
  UnusedPageTypesReport: Dynamic\Core\Report\UnusedPageTypesReport
  SpiffLinkableUpdateTask: Dynamic\Core\Task\SpiffLinkableUpdateTask
  CompanyConfigTask: Dynamic\Core\Task\CompanyConfigTask
  PreviewExtensionMigrationTask: Dynamic\Core\Task\PreviewExtensionMigrationTask
  DynamicHomePageTest: Dynamic\Core\Test\DynamicHomePageTest
  ContactPageTest: Dynamic\Core\Test\ContactPageTest
  FormPageTest: Dynamic\Core\Test\FormPageTest
  YoutubeFieldTest: Dynamic\Core\Test\YoutubeFieldTest
  YoutubeFieldTest_Validator: Dynamic\Core\Test\YoutubeFieldTest_Validator
  YoutubeFieldTest_Controller: Dynamic\Core\Test\YoutubeFieldTest_Controller
  NewsArticleTest: Dynamic\Core\Test\NewsArticleTest
  LandingPageTest: Dynamic\Core\Test\LandingPageTest
  DetailPageTest: Dynamic\Core\Test\DetailPageTest
  DC_Test: Dynamic\Core\Test\DC_Test
  BasicPageTest: Dynamic\Core\Test\BasicPageTest
