---
Name: core
---
SectionPage:
  singluar_name: "Section Page"
  plural_name: "Section Pages"
  description: "Section Landing Page, uses Flexslider and Spiffs"
  hide_ancestor: "SectionPage"
ChildListPage:
  singular_name: "Child List Page"
  plural_name: "Child List Pages"
  description: "This page lists its sub pages"
  hide_ancestor: "ChildListPage"
CollectionPage:
  singular_name: "Collection Page"
  plural_name: "Collection Pages"
  description: "Displays a searchable, paginated list of content"
  hide_ancestor: "CollectionPage"
  allowed_children: ["DetailPage"]
  default_child: "DetailPage"
DetailPage:
  singular_name: "Detail Page"
  plural_name: "Detail Pages"
  description: "Rich content page, includes images and slides"
  hide_ancestor: "Page"
HolderPage:
  singular_name: "Group Page"
  plural_name: "Group Pages"
  hide_ancestor: "HolderPage"
HolderItem:
  singular_name: "Holder Item"
  plural_name: "Holder Items"
AlbumPage:
  singular_name: 'Album Page'
  plural_name: 'Album Pages'
  description: 'Album holding images'
NewsArticle:
  singular_name: 'News Article'
  plural_name: 'News Articles'
  description: 'Article for the News section'
LeftAndMain:
  extra_requirements_css: [dynamic-core/css/leftandmainextracss.css]