---
Name: core
---
SiteTree:
  db:
# Core Site Tree
    SubTitle: Varchar(255)
  extensions:
    - CoreSiteTree
SiteConfig:
  db:
# Company Config
    CompanyName: Varchar(200)
    PhoneNumber: Varchar(20)
    EmailAddress: Varchar(100)
    ShowDirections: Boolean
    Hours: Text
# Settings Config
    ShareThisPublisherID: Varchar(255)
# Template Config
    TitleLogo: enum('Logo, Title', 'Title')
    LogoDimensionOverride: Boolean
    LogoWidth: Int
    LogoHeight: Int
  extensions:
    - CompanyConfig
    - TemplateConfig
    - SettingsConfig
DetailPage:
  db:
# Preview Extension
    PreviewTitle: HTMLVarchar
    Abstract: HTMLText
    AbstractFirstParagraph: Boolean
  extensions:
    - PreviewExtension
    - FlexSlider
SectionPage:
  extensions:
    - FlexSlider
    - SpiffManager
  singluar_name: "Section Page"
  plural_name: "Section Pages"
  description: "Section Landing Page, uses Flexslider and Spiffs"
  hide_ancestor: "SectionPage"
VirtualPage:
  extensions:
    - VirtualPageExtension
ErrorPage:
  extensions:
    - HideExtension
ChildListPage:
  singular_name: "Child List Page"
  plural_name: "Child List Pages"
  description: "This page lists its sub pages"
  hide_ancestor: "ChildListPage"
CollectionPage:
  singular_name: "Collection Page"
  plural_name: "Collection Pages"
  description: "Displays a searchable, paginated list of content"
  hide_ancestor: "CollectionPage"
  allowed_children: ["DetailPage"]
  default_child: "DetailPage"
DetailPage:
  singular_name: "Detail Page"
  plural_name: "Detail Pages"
  description: "Rich content page, includes images and slides"
  hide_ancestor: "Page"
HolderPage:
  singular_name: "Group Page"
  plural_name: "Group Pages"
  hide_ancestor: "HolderPage"
